version: "3" 
services:
  mysqldb:
    image: mysql/mysql-server:8.0.20
    container_name: local_mysql
    volumes:
      - mysql_volume:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - '3306'
volumes:
  mysql_volume:
